config/routes.rb
Rails.application.routes.draw do
  get 'books/index'

  get 'books', to: 'groups#index'
  root 'books#index'

  get 'books/new'
  post 'books', to: 'books#create'

  get 'books/:id', to: 'books#show', as: 'book'

  get 'books/:id/edit', to: 'books#edit', as: 'book_edit'
  patch 'books/:id', to: 'books#update'

  delete 'books/:id', to: 'books#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: %w[Prestado Estante]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[show edit]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @statuses = Book.statuses.keys.to_a
  end

  def create
    @book = Book.create(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: "El libro ha sido creado"}
      else
        format.html  {render :new}
      end
    end
  end

  def edit
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end
  
  def book_params
    params.require(:book).permit(:title, :author, :status, :lend_date, :return_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <%= render '/shared/form', book: @book %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Título</th>
        <th>Autor</th>
        <th>Estado</th>
        <th>Fecha de préstamo</th>
        <th>Fecha de devolución</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr> 
            <td><%= book.id %></td>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.status %></td>
          <td><%= book.lend_date %></td>
          <td><%= book.return_date %></td>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', book_edit_path(book.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Crear nuevo Libro', books_new_path, class: 'btn btn-success' %>
</div>

app/views/books/new.html.erb
<%= render '/shared/form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>Fecha de préstado:</strong>
  <%= @book.lend_date %>
</p>

<p>
  <strong>Fecha de devolución:</strong>
  <%= @book.return_date %>
</p>

<%= link_to 'Ir al root', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E26Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
    <% if book.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este libro no se pudo crear por las siguientes razones</h2>
            <ul>
                <% book.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :title, "Título" %>
        <%= f.text_field :title, placeholder: "el re título", class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :author, "Autor" %>
        <%= f.text_field :author, class: 'form-control' %>
    </div>
  
    <div class="form-group">
        <%= f.label :status, "Estado" %>
        <%= f.select :status, options_for_select(@statuses),{:include_blank => true}, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :lend_date, "Fecha de préstamo" %>
        <%= f.datetime_select :lend_date, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :return_date, "Fecha de devolución" %>
        <%= f.datetime_select :return_date, class: 'form-control' %>
    </div>

    <div class = 'actions'>
        <%= f.submit %>
    </div>

<% end %>